# Scenario Name 
scenario: "BASELINEKenya"


# for country wise - comment out the other counties  and keep the country that is being modelled eg: ken; make crossborderTrade: False transmission_planned: False and comment out 
# FOR NUCLEAR - imp - CHNAGE SCENARIO NAME AND IN NO INVEST TECHNOLOGIES - UNCOMMENT URN
# IN USER DEFINED CAPACITY - UNCOMMENT URN FOR KEN, TZA

# Temporal Parameters 
startYear: 2022
endYear: 2050
daytype: False
dayparts:
# daypart : [start_hour (inclusive), end_hour (exclusive)]
  D1: [1, 5]
  D2: [5, 9]
  D3: [9, 13]
  D4: [13, 17]
  D5: [17, 21]
  D6: [21, 25]
seasons:
# season : [month 1, month 2, ...] (all inclusive)
  S1: [1, 2]
  S2: [3, 4, 5]
  S3: [6, 7, 8, 9]
  S4: [10, 11, 12]

timeshift: 3 # value between -11 and 12
  
# Spatial Parameters 
geographic_scope:
  - "KEN"
  #- "TZA"
  #- "ETH"
  #- "UGA"

# Set to True if transmission should be included
crossborderTrade: True

# Set to True if existing transmission capacities should be included
# from the Global Transmission Database (Brinkerink et al., 2024).
transmission_existing: True

# Set to True if planned transmission capacities should be included
# from the Global Transmission Database (Brinkerink et al., 2024).
transmission_planned: False


# Set to True if existing storage capacities should be included
# from the Global Energy Storage Database (DOE/Sandia).
# If custom nodes are defined in 'nodes_to_add' and you want to assign
# GESDB data to custom nodes you'll have to update 'GESDB_region_mapping'
# in 'resources/data/custom'.
storage_existing: True

# Set to True if planned storage capacities should be included
# from the Global Energy Storage Database (DOE/Sandia).
# If custom nodes are defined in 'nodes_to_add' and you want to assign
# GESDB data to custom nodes you'll have to update 'GESDB_region_mapping'
# in 'resources/data/custom'.
storage_planned: True

# Emission Parameters 
emission_penalty: 
# - [EMISSION, COUNTRY, START_YEAR, END_YEAR, VALUE]
# EXAMPLE:  - ["CO2", "IND", 2020, 2050, 2.1]
# where VALUE is in M$/MT CO2

# Investment Parameters 
no_invest_technologies: 
  - "OTH"
  - "COG" 
  - "PET"
  - "COA"
  - "OCG"
  #- "OIL"
  - "URN"
  - "WOF"
  #- "CCG"
  - "WAV"
  - "LDS"

# Result Parameters 
results_by_country: True

# solver parameters
solver: "gurobi" # cbc, cplex, gurobi

user_defined_capacity:
# technology: [capacity, 
#              build_year, 
#              first_year_of_expansion, 
#              build_rate_per_year, 
#              capex_cost, 
#              efficiency]
# EXAMPLE:  PWRCOAINDWE01: [8, 2000, 2025, 5, 1100, 35]
# Units are in GW (capacity/build_rate_per_year), m$/GW (capex_cost), 
# % (efficiency).
  #PWRWONKENXX01: [.2, 2022, 2025, 0, 1800, 100]
  #PWRSPVTZAXX01: [.15, 2026, 2028, 5, 820, 33]
  #PWRSPVETHXX01: [.10, 2026, 2028, 5, 820, 33]
  #PWRBIOUGAXX01: [.01, 2010, 2022, 0.1, 2100, 33]
  #PWRSPVUGAXX01: [.06, 2015, 2026, 5, 820, 33]
  #PWRHYDTZAXX01: [.08, 2022, 2030, 3, 2100, 90]
  #PWRHYDKENXX01: [.025, 2022, 2030, 1, 2100, 90]
  #PWRHYDETHXX01: [.025, 2022, 2030, 3, 2100, 90]
  #PWRHYDUGAXX01: [.025, 2022, 2030, 3, 2100, 90]
  #PWRWASKENXX01: [.1, 2022, 2030, 1, 800, 33]
  #PWRHYDUGAXX01: [.1, 2022, 2030, 1, 800, 90]
  #PWROILTZAXX01: [.01, 1990, 2022, 0, 3800, 33]
  #PWRHYDUGAXX01: [.7, 2023, 2030, 1, 800, 33]
  #PWROILUGAXX01: [.01, 2000, 2022, 0.001, 800, 33]
  #PWRURNKENXX01: [.5, 2035, 2035, 0.5, 4000, 33]
  #PWRURNTZAXX01: [.5, 2035, 2035, 0.5, 4000, 33]
  

user_defined_capacity_transmission:
# entry: [technology,
#         capacity, 
#         build_year, 
#         first_year_of_expansion, 
#         final_year_of_expansion,   
#         build_rate_per_year, 
#         capex_cost,
#         annual_fixed_O&M_cost,
#         variable_O&M_cost,
#         efficiency]
# EXAMPLE:  trn1: [TRNINDEAINDNE, 5, 1975, 2025, 2025, 0, 350, 13, 4, 95]
# Per technology, only the capacity, build_year, first_year_of_expansion, 
# final_year_of_expansion and build_rate_per_year parameters can deviate
# from each other. For all other parameters only the last entry will be used.
  trn1: [TRNTZAXXKENXX, 2, 2025, 2025, 2025, 0, 350, 13, 4, 95]
  trn2: [TRNKENXXTZAXX, 2, 2025, 2025, 2025, 0, 350, 13, 4, 95]
  trn3: [TRNETHXXKENXX, .2, 2010, 2025, 2025, 0, 350, 13, 4, 95]
  trn4: [TRNKENXXETHXX, .2, 2010, 2025, 2025, 0, 350, 13, 4, 95]
  trn5: [TRNUGAXXTZAXX, .2, 2010, 2026, 2050, 0, 350, 13, 4, 95]
  trn6: [TRNTZAXXUGAXX, .2, 2010, 2026, 2050, 0, 350, 13, 4, 95]
  trn7: [TRNKENXXUGAXX, .1, 2010, 2026, 2050, 0, 350, 13, 4, 95]
  trn8: [TRNUGAXXKENXX, .1, 2010, 2026, 2050, 0, 350, 13, 4, 95]
  #trn9: [TRNETHXXUGAXX, 1, 2026, 2026, 2050, 1, 350, 13, 4, 95]
  #trn10: [TRNUGAXXETHXX, 1, 2026, 2026, 2050, 1, 350, 13, 4, 95]
  #trn11: [TRNTZAXXETHXX, 1, 2026, 2026, 2050, 1, 350, 13, 4, 95]
  #trn12: [TRNETHXXTZAXX, 1, 2026, 2026, 2050, 1, 350, 13, 4, 95]

user_defined_capacity_storage:
# entry: [technology, 
#         capacity, 
#         build_year, 
#         first_year_of_expansion, 
#         build_rate_per_year, 
#         capex_cost, 
#         annual_fixed_O&M_cost, 
#         variable_O&M_cost, 
#         roundtrip_efficiency]
# EXAMPLE:  sto1: [PWRSDSINDWE01, 2, 2010, 2025, 3, 1800, 40, 0, 87]
# Per technology, only the capacity and build_year
# parameters can deviate from each other. For all other
# parameters only the last entry will be used.
# Units are in GW (capacity/build_rate_per_year), 
# m$/GW (capex_cost/annual_fixed_O&M_cost), 
# $/MWh (variable_O&M_cost), % (roundtrip_efficiency).
  sto1: [PWRLDSKENXX01, .1, 2026, 2026, .1, 3794, 20.2, 0.58, 80]
  sto2: [PWRLDSETHXX01, .1, 2026, 2026, .1, 3794, 20.2, 0.58, 80]
  sto3: [PWRLDSTZAXX01, .1, 2026, 2026, .1, 3794, 20.2, 0.58, 80]
  sto4: [PWRLDSUGAXX01, .1, 2026, 2026, .1, 3794, 20.2, 0.58, 80]
  sto5: [PWRSDSKENXX01, .1, 2026, 2026, .2, 968, 24, 0, 85]
  sto6: [PWRSDSETHXX01, .1, 2026, 2026, 1.5, 968, 24, 0, 85]
  sto7: [PWRSDSTZAXX01, .1, 2026, 2026, .5, 968, 24, 0, 85]
  sto8: [PWRSDSUGAXX01, .1, 2026, 2026, .5, 968, 24, 0, 85]
  #sto9: [PWRSDSUGAXX01, 1, 2040, 2040, .5, 900, 24, 0, 85]

transmission_parameters:
# technology_group: [Line CAPEX, 
#                    Converter pair CAPEX, 
#                    Line losses, 
#                    AC/DC Converter pair losses, 
#                    Fixed O&M costs, 
#                    Variable O&M costs]
# Units are in $2020/MW/KM (Line CAPEX), $2020/MW (Converter pair CAPEX),
# %/1000km (Line losses), % (AC/DC Converter pair losses), 
# % of total CAPEX/yr (Fixed O&M costs), $/MWh (Variable O&M costs).
  HVAC: [779, 95400, 6.75, 0, 3.5, 4]
  HVDC: [238, 297509, 3.5, 1.3, 3.5, 4]
  HVDC_subsea: [295, 297509, 3.5, 1.3, 3.5, 4]

storage_parameters:
# technology_group: [capex_cost,
#                    annual_fixed_O&M_cost,
#                    variable_O&M_cost,
#                    roundtrip_efficiency,
#                    duration]
# EXAMPLE:  SDS: [1938, 44.25, 0, 85, 4] 
# Units are in m$/GW (capex_cost, annual_fixed_O&M_cost), $/MWh (variable_O&M_cost),
# % (roundtrip_efficiency), hours (duration = storage capacity (GWh)/Power rating (GW)).
  SDS: [968, 24, 0, 85, 4]
  LDS: [3794, 20.2, 0.58, 80, 10]
  
nodes_to_add:
# - "AAAXX" where AAA is a 3-letter country code, 
# specified in the "geographic scope" 
# and XX is a 2-letter sub-regional node code. 
# E.g. - "IDNSM" for a sub-regional node in Sumatra, Indonesia.

nodes_to_remove:
# - "AAAXX" where AAA is a 3-letter country code, and XX is a 2-letter 
# sub-national code.
# E.g. - "INDNO" for the Northern India region that is part of the default OSeMOSYS
# Global workflow.

reserve_margin:
# RESERVE_MARGIN: [PERCENTAGE, START_YEAR, END_YEAR]
# Years for which there is no PERCENTAGE value will be interpolated
# EXAMPLE:  RM1: [10, 2025, 2050]
  RM1: [10, 2030, 2050]

reserve_margin_technologies:
# TECHNOLOGY: PERCENTAGE,
# Specify the share of capacity (%) per technology that can contribute to the
# reserve margin. Technologies that are not listed are excluded from contributing.
# EXAMPLE:  CCG : 90
  BIO : 90
  CCG : 90
  COA : 90
  #CCS : 90
  COG : 50
  #CSP : 30
  GEO : 90
  HYD : 70
  OCG : 90
  OIL : 90
  OTH : 90
  PET : 90
  URN : 90
  WAS : 90
  WAV : 10
  WOF : 10
  WON : 10
  SPV : 10
  LDS : 50
  SDS : 50    

emission_limit:
# - [EMISSION, COUNTRY, TYPE, YEAR, VALUE]
# where VALUE is emissions in million tonnes of CO2-equivalent and YEAR is  
# when that constraint must be adhered to. All years between multiple emission 
# constraints will be interpolated if TYPE is set to "LINEAR". If "POINT" is used
# it means that a singular year value is set without interpolation occuring in
# previous target years. A combination of TYPE targets can be set per EMISSION and
# COUNTRY yet only a single target per YEAR.
# EXAMPLE: - ["CO2", "IND", "LINEAR", 2050, 0]

min_generation_factors:
# TECHNOLOGY: [VALUE, COUNTRY, YEAR]
# where VALUE is minimum utilization (PJ) of a given technology. This can be 
# used to constrain power plant output (generation), for example, to calibrate historical
# generation values.
# EXAMPLE:  OCG: [50, "IND", 2021]
  #OIL: [5, "KEN", 2023]
  #HYD: [10, "KEN", 2022]
  #HYD: [10, "KEN", 2023]
  #HYD: [12, "KEN", 2024]
  #HYD: [12, "KEN", 2025]
  WON1: [3, "KEN", 2022]
  WON2: [3, "KEN", 2023]
  WON3: [2, "KEN", 2024]
  WON8: [2, "KEN", 2025]
  WON9: [2, "KEN", 2026]
  WON10: [2, "KEN", 2027]
  WON11: [2, "KEN", 2028]
  WON12: [2, "KEN", 2029]
  WON13: [2, "KEN", 2030]
  SPV8: [1, "KEN", 2023]
  SPV6: [1, "KEN", 2024]
  SPV7: [1, "KEN", 2025]
  SPV9: [1, "KEN", 2026]
  SPV10: [1, "KEN", 2027]
  SPV11: [1, "KEN", 2028]
  SPV12: [1, "KEN", 2029]
  #WON: [2, "KEN", 2025]
  #WON: [7, "KEN", 2023]
  #WON: [7, "KEN", 2024]
  #WON: [7, "KEN", 2025]
  #BIO: [1, "KEN", 2023]
  #WON: [7, "KEN", 2023]
  #SPV: [2, "KEN", 2023]
  #GEO: [21, "KEN", 2023]
  #OIL: [4, "KEN", 2022]
  #HYD: [8, "KEN", 2022]
  #WON: [7, "KEN", 2022]
  #SPV: [1.5, "KEN", 2022]
  #GEO: [15, "KEN", 2022]
  #OIL: [4, "KEN", 2023]
  #HYD: [8, "KEN", 2022]
  #WON: [7, "KEN", 2023]
  #SPV: [1.5, "KEN", 2022]
  #GEO: [15, "KEN", 2023]
  #OIL: [4, "KEN", 2024]
  #HYD: [8, "KEN", 2022]
  #WON: [7, "KEN", 2024]
  #SPV: [1.5, "KEN", 2022]
  #GEO: [15, "KEN", 2024]
  #BIO: [0.9, "KEN", 2022]
  #OIL: [0.1, "TZA", 2022]
  #OCG: [23, "TZA", 2022]
  #CCG: [20, "TZA", 2022]
  #CCG: [11, "TZA", 2023]
  #HYD: [10, "TZA", 2022]
  #SPV: [0.1, "TZA", 2022]
  #BIO: [0.3, "TZA", 2022]
  #OIL: [0.08, "TZA", 2020]
  #OCG: [19, "TZA", 2020]
  #CCG: [.8, "TZA", 2020]
  #HYD9: [3.5, "TZA", 2022]
  #HYD10: [3.5, "TZA", 2023]
  #SPV: [0.08, "TZA", 2020]
  #BIO: [0.2, "TZA", 2020]
  #HYD: [50, "ETH", 2022]
  #SPV: [0.1, "ETH", 2022]
  #WON: [2, "ETH", 2022]
  HYD1: [30, "ETH", 2022]
  HYD2: [30, "ETH", 2023]
  HYD6: [30, "ETH", 2024]
  HYD7: [30, "ETH", 2025]
  HYD9: [30, "ETH", 2025]
  HYD10: [30, "ETH", 2026]
  HYD11: [30, "ETH", 2027]
  HYD12: [30, "ETH", 2028]
  HYD13: [30, "ETH", 2029]
  HYD14: [30, "ETH", 2030]
  HYD15: [32, "ETH", 2031]
  HYD16: [32, "ETH", 2032]
  HYD17: [32, "ETH", 2033]
  HYD18: [32, "ETH", 2034]
  HYD19: [32, "ETH", 2035]
  HYD20: [32, "ETH", 2036]
  HYD21: [32, "ETH", 2037]
  HYD22: [32, "ETH", 2038]
  HYD23: [32, "ETH", 2039]
  HYD24: [32, "ETH", 2040]
  HYD25: [33, "ETH", 2041]
  HYD26: [33, "ETH", 2042]
  HYD27: [33, "ETH", 2043]
  HYD28: [33, "ETH", 2044]
  HYD29: [33, "ETH", 2045]
  HYD30: [33, "ETH", 2046]
  HYD31: [33, "ETH", 2047]
  HYD32: [33, "ETH", 2048]
  HYD33: [33, "ETH", 2049]
  HYD34: [33, "ETH", 2050]
  WON4: [1, "ETH", 2022]
  WON5: [1, "ETH", 2023]
  WON6: [1.2, "ETH", 2024]
  WON7: [1.2, "ETH", 2025]
  SPV5: [0.1, "ETH", 2022]
  HYD3: [8, "UGA", 2022]
  HYD4: [8, "UGA", 2023]
  HYD5: [8, "UGA", 2024]
  HYD8: [8, "UGA", 2025]
  HYD35: [8, "UGA", 2026]
  HYD36: [8, "UGA", 2027]
  HYD37: [8, "UGA", 2028]
  HYD38: [8, "UGA", 2029]
  HYD39: [8, "UGA", 2030]
  HYD40: [8, "UGA", 2031]
  HYD41: [8, "UGA", 2032]
  HYD42: [8, "UGA", 2033]
  HYD43: [8, "UGA", 2034]
  HYD44: [8, "UGA", 2035]
  HYD45: [8, "UGA", 2036]
  HYD46: [8, "UGA", 2037]
  HYD47: [8, "UGA", 2038]
  HYD48: [8, "UGA", 2039]
  HYD49: [8, "UGA", 2040]
  HYD50: [8, "UGA", 2041]
  HYD51: [8, "UGA", 2042]
  HYD52: [8, "UGA", 2043]
  HYD53: [8, "UGA", 2044]
  HYD54: [8, "UGA", 2045]
  HYD55: [8, "UGA", 2046]
  HYD56: [8, "UGA", 2047]
  HYD57: [8, "UGA", 2048]
  HYD58: [8, "UGA", 2049]
  HYD59: [8, "UGA", 2050]
  #HYD6: [8, "UGA", 2025]
  #HYD2: [14, "UGA", 2023]
  #SPV: [0.1, "ETH", 2022]
  #BIO: [0.08, "ETH", 2022]
  #OIL: [0.5, "UGA", 2023]
  #HYD: [18, "UGA", 2023]
  #BIO: [2, "UGA", 2023]
  SPV1: [0.2, "UGA", 2022]
  SPV2: [0.2, "UGA", 2023]
  SPV3: [0.2, "UGA", 2024]
  SPV4: [0.2, "UGA", 2025]
  #OIL: [0.45, "UGA", 2020]
  #HYD: [15, "UGA", 2020]
  #BIO: [1.2, "UGA", 2020]
  #SPV: [0.3, "UGA", 2020]


  
max_availability_factors:
# [COUNTRY/NODE, TECHNOLOGY, START_YEAR, END_YEAR, VALUE]
# where VALUE is percentage (%) MAX availability of a given technology. This overwrites
# the default values from availability_factors.csv in resources/data. This parameter can
# be used to constrain the maximum output of technologies to, for example, mimic 
# max generation policy targets.
# EXAMPLE: - ["IND", 'COA', 2030, 2050, 25]
  #- ["KEN", 'HYD', 2022, 2022, 30]
  #- ["KEN", 'HYD', 2022, 2022, 80]
  #- ["KEN", 'OCG', 2025, 2050, 1]
  #- ["KEN", 'CCG', 2015, 2050, 1]
  #- ["KEN", 'OIL', 2025, 2050, 1]
  #- ["TZN", 'OCG', 2026, 2050, 1]
  #- ["TZA", 'CCG', 2022, 2025, 70]
  #- ["TZA", 'HYD', 2022, 2023, 60]
  - ["TZA", 'HYD', 2024, 2025, 30]
  #- ["KEN", 'WON', 2022, 2022, 190]
  - ["KEN", 'WON', 2022, 2023, 280]
  - ["KEN", 'WON', 2024, 2025, 190]
  - ["KEN", 'HYD', 2022, 2023, 80]
  - ["KEN", 'HYD', 2023, 2030, 80]
  - ["KEN", 'SPV', 2023, 2023, 150]
  #- ["KEN", 'OCG', 2022, 2023, 80]
  #- ["KEN", 'CCG', 2022, 2023, 80]
  #- ["KEN", 'WON', 2023, 2023, 190]
  #- ["KEN", 'WON', 2024, 2024, 190]
  #- ["KEN", 'WON', 2024, 2024, 190]
  #- ["KEN", 'WON', 2025, 2025, 190]
  - ["KEN", 'GEO', 2022, 2025, 60]
  - ["KEN", 'BIO', 2022, 2025, 15]
  #- ["ETH", 'WAS', 2022, 2025, 0]
  - ["ETH", 'BIO', 2022, 2025, 0]
  #- ["ETH", 'OIL', 2022, 2025, 0]
  - ["ETH", 'WON', 2022, 2025, 150]
  #- ["ETH", 'OIL', 2022, 2025, 30]
  #- ["ETH", 'WAS', 2022, 2030, 0]
  - ["UGA", 'GEO', 2022, 2050, 30]
  - ["ETH", 'HYD', 2022, 2030, 60]
  - ["ETH", 'HYD', 2031, 2050, 80]
  - ["UGA", 'HYD', 2022, 2022, 50]
  - ["UGA", 'HYD', 2023, 2024, 30]
  - ["UGA", 'HYD', 2025, 2050, 35]
  - ["UGA", 'SPV', 2022, 2025, 150]
  - ["UGA", 'OIL', 2022, 2025, 30]
  


 
fossil_capacity_targets:
# [NODE, TECHNOLOGY, START_YEAR, END_YEAR, SENSE, VALUE]
# where VALUE is the absolute (GW) capacity constraint and SENSE sets the type of constraint.
# E.g. 'ABS' sets a fixed value, 'MIN' sets a minimum capacity value and 'MAX' sets a maximum
# capacity value. Note that in case 'ABS' or 'MAX' is applied, the given value needs to be 
# higher than the residual capacity of that technology in the given year otherwise the workflow
# will not complete. Targets can only be set at the nodal level.
# EXAMPLE: - ["INDNE", 'CCG', 2040, 2050, 'MIN', 10]
  #- ["KENXX", 'OIL', 2030, 2050, 'ABS', 1]
  #- ["ETHXX", 'OCG', 2015, 2050, 'ABS', 0]
  #- ["ETHXX", 'CCG', 2015, 2050, 'ABS', 0]



re_targets:
# TARGET: [COUNTRY/NODE, [TECHNOLOGY], START_YEAR, END_YEAR, VALUE]
# E.g. TO1: ["IND", [], "PCT", 2030, 2040, 60]
# E.g. TO2: ["INDSO", ['WOF', 'WON'], "PCT", 2025, 2045, 15]
# E.g. TO3: ["INDSO", ['WOF'], "ABS", 2040, 2050, 200]
# Targets can be set in absolute terms ("ABS", VALUE = GW) or in relative terms 
# ("PCT", VALUE = %) where targets in relative terms represent the share of generation.
# For "PCT", targets can be set at national (e.g. "IND") and nodal levels (e.g. "INDSO")
# whereas "ABS" can only be set at nodal levels. For "PCT", a single technology can 
# be set for the target (e.g. ["WOF"]) a technology subset can be set (e.g. ['WOF', 'WON'])
# or the TECHNOLOGY list can be left empty (e.g. []) as such that all renewable
# technologies contribute to the target. For "ABS", only one technology can be 
# selected per target. Note that a combination of targets can be set that affect
# the same countries/nodes/technologies. This can be computationally intensive.
# EXAMPLE:  T01: ["", [], "PCT", 2048, 2050, 95]
# EXAMPLE:  T02: ["IND", [], "PCT", 2030, 2040, 60]
# EXAMPLE:  T03: ["INDSO", ['WOF','WON'], "PCT", 2025, 2045, 15]
# EXAMPLE:  T04: ["INDSO", ['WOF'], "ABS", 2040, 2050, 100]
  #T01: ["", [], "PCT", 2040, 2050, 60]
  #T01: ["KENXX", ['SPV','WON'], "PCT", 2026, 2050, 30]
  #T01: ["TZAXX", [], "PCT", 2030, 2050, 30]
  #T03: ["ETHXX", ['SPV','WON'], "PCT", 2026, 2050, 30]
  #T04: ["UGAXX", ['SPV','WON'], "PCT", 2026, 2050, 30]
  #T01: ["KENXX", ['WON'], "PCT", 2026, 2050, 30]
  #T01: ["TZAXX", ['WON'], "PCT", 2026, 2050, 30]
  #T01: ["ETHXX", ['WON'], "PCT", 2026, 2050, 30]
  #T01: ["UGAXX", ['WON'], "PCT", 2026, 2050, 30]


